name: CI to Docker hub

on:
  push:
    branches: [ api-dev ]
  pull_request:
    branches: [ api-dev ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
                  
      - name: Login to DockerHub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build test
        if: github.event.inputs.tag
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
#           platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          platforms: ${{github.event.inputs.tags}}
          push: false
          tags: |
            dcflachs/wio_link:test
            dcflachs/wio_link:nightly-${{ steps.date.outputs.date }}

      - name: Build and push
        id: docker_build
        if: false == github.event.inputs.tag
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
#           platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          platforms: linux/amd64,linux/arm/v6
          push: true
          tags: |
            dcflachs/wio_link:test
            dcflachs/wio_link:nightly-${{ steps.date.outputs.date }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
